version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - mongoUri=${mongoUri}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CLUSTER=${MONGO_CLUSTER}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  stripe-listen:
    image: stripe/stripe-cli
    entrypoint: >
      sh -c "stripe listen --forward-to backend:8080/stripe/webhook"
    environment:
      - STRIPE_API_KEY=sk_test_51Qw1U8BCqcG9036LxgVOL303UwhUG4htSxC2qJv8Uzs1GxJnCDKdnnyJ3E9LH0uTepVPKoHurASZ7wLizh5tDeEw00SkAMJ36h  # ✅ Or use CLI login token
      - STRIPE_DEVICE_NAME=docker-listener
    depends_on:
      - backend